{{- if .Values.configservice.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "apollo.configservice.fullname" . }}
  labels:
    app: {{ template "apollo-helm.name" . }}
    chart: {{ template "apollo-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "{{ .Values.configservice.name }}"
spec:
  replicas: {{ .Values.configservice.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "apollo-helm.name" . }}
        release: {{ .Release.Name }}
        component: "{{ .Values.configservice.name }}"
    spec:
#      serviceAccountName: {{ template "apollo.serviceAccountName.configservice" . }}
      containers:
        - name: {{ template "apollo-helm.name" . }}-{{ .Values.configservice.name }}
          image: "{{ .Values.configservice.image.repository }}:{{ .Values.configservice.image.tag }}"
          imagePullPolicy: "{{ .Values.configservice.image.pullPolicy }}"
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              value: "service-apollo-config-server-dev.sre"
          {{- if .Values.configservicemysql.enabled }}
            - name: DATASOURCES_URL
              value: "jdbc:mysql://apollo-configservicemysql:3306/{{ .Values.configservicemysql.mysqlDatabase }}?characterEncoding=utf8"
            - name: DATASOURCES_USERNAME
              value: "{{ .Values.configservicemysql.mysqlUser }}"
            - name: DATASOURCES_PASSWORD
              value: "{{ .Values.configservicemysql.mysqlPassword }}"
            {{- end }}
            {{- range $key, $value := .Values.configservice.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 90
          resources:
{{ toYaml .Values.configservice.resources | indent 12 }}
#          volumeMounts:
#            - name: config-volume
#              mountPath: /apollo-config-server/config/application-github.properties
#              subPath: application-github.properties
    {{- if .Values.configservice.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.configservice.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.configservice.tolerations }}
      tolerations:
{{ toYaml .Values.configservice.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.configservice.affinity }}
      affinity:
{{ toYaml .Values.configservice.affinity | indent 8 }}
    {{- end }}
#      volumes:
#        - name: config-volume
#          configMap:
#            name: {{ if .Values.configservice.configMapOverrideName }}{{ .Release.Name }}-{{ .Values.configservice.configMapOverrideName }}{{- else }}{{ template "apollo.configservice.fullname" . }}{{- end }}
#            items:
#              - key: application-github.properties
#                path: application-github.properties
{{- end }}
